client_config_backend: settings
client_config:
  client_id: 670466884927-75lr9p83uu78ij825u1lvc72erbrfuqo.apps.googleusercontent.com
  client_secret: xbSPIx4c2BVYrFAoyULWaB9y

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install